#[derive(Debug, Clone, Copy, enum_iterator::Sequence, Hash, PartialEq)]
pub enum Category {
  AudioVideo,
  Development,
  EducationScience,
  Games,
  Graphics,
  Network,
  Office,
  Settings,
  System,
  Utility,
  Uncategorized,
}

pub fn category_string(cat: Category) -> &'static str {
  match cat {
    Category::AudioVideo => "Audio/Video",
    Category::Development => "Development",
    Category::EducationScience => "Education/Science",
    Category::Games => "Games",
    Category::Graphics => "Graphics",
    Category::Network => "Network",
    Category::Office => "Office",
    Category::Settings => "Settings",
    Category::System => "System",
    Category::Utility => "Utility",
    Category::Uncategorized => "Uncategorized",
  }
}
pub fn category_idx(cat: Category) -> usize {
  match cat {
    Category::AudioVideo => 1,
    Category::Development => 2,
    Category::EducationScience => 3,
    Category::Games => 4,
    Category::Graphics => 5,
    Category::Network => 6,
    Category::Office => 7,
    Category::Settings => 8,
    Category::System => 9,
    Category::Utility => 10,
    Category::Uncategorized => 11,
  }
}

pub static CATEGORY_MAP: phf::Map<&'static str, Category> = phf::phf_map! {
  "Audio" => Category::AudioVideo,
  "Video" => Category::AudioVideo,
  "AudioVideo" => Category::AudioVideo,
  "Midi" => Category::AudioVideo,
  "Music" => Category::AudioVideo,
  "Mixer" => Category::AudioVideo,
  "Sequencer" => Category::AudioVideo,
  "Tuner" => Category::AudioVideo,
  "TV" => Category::AudioVideo,
  "AudioVideoEditing" => Category::AudioVideo,
  "Player" => Category::AudioVideo,
  "Recorder" => Category::AudioVideo,
  "DiscBurning" => Category::AudioVideo,
  "Development" => Category::Development,
  "Building" => Category::Development,
  "Database" => Category::Development,
  "Debugger" => Category::Development,
  "IDE" => Category::Development,
  "GUIDesigner" => Category::Development,
  "Profiling" => Category::Development,
  "RevisionControl" => Category::Development,
  "Translation" => Category::Development,
  "Education" => Category::EducationScience,
  "Science" => Category::EducationScience,
  "Art" => Category::EducationScience,
  "Construction" => Category::EducationScience,
  "Languages" => Category::EducationScience,
  "ArtificialIntelligence" => Category::EducationScience,
  "Astronomy" => Category::EducationScience,
  "Biology" => Category::EducationScience,
  "Chemistry" => Category::EducationScience,
  "ComputerScience" => Category::EducationScience,
  "DataVisualization" => Category::EducationScience,
  "Economy" => Category::EducationScience,
  "Electricity" => Category::EducationScience,
  "Geography" => Category::EducationScience,
  "Geology" => Category::EducationScience,
  "Geoscience" => Category::EducationScience,
  "History" => Category::EducationScience,
  "Humanities" => Category::EducationScience,
  "ImageProcessing" => Category::EducationScience,
  "Literature" => Category::EducationScience,
  "Maps" => Category::EducationScience,
  "Math" => Category::EducationScience,
  "NumericalAnalysis" => Category::EducationScience,
  "MedicalSoftware" => Category::EducationScience,
  "Physics" => Category::EducationScience,
  "Robotics" => Category::EducationScience,
  "Spirituality" => Category::EducationScience,
  "Sports" => Category::EducationScience,
  "ParallelComputing" => Category::EducationScience,
  "Engineering" => Category::EducationScience,
  "Electronics" => Category::EducationScience,
  "Amusement" => Category::Games,
  "Game" => Category::Games,
  "Games" => Category::Games,
  "ActionGame" => Category::Games,
  "AdventureGame" => Category::Games,
  "ArcadeGame" => Category::Games,
  "BoardGame" => Category::Games,
  "BlocksGame" => Category::Games,
  "CardGame" => Category::Games,
  "KidsGame" => Category::Games,
  "LogicGame" => Category::Games,
  "RolePlaying" => Category::Games,
  "Shooter" => Category::Games,
  "Simulation" => Category::Games,
  "SportsGame" => Category::Games,
  "StrategyGame" => Category::Games,
  "Graphics" => Category::Graphics,
  "2DGraphics" => Category::Graphics,
  "VectorGraphics" => Category::Graphics,
  "RasterGraphics" => Category::Graphics,
  "3DGraphics" => Category::Graphics,
  "Scanning" => Category::Graphics,
  "OCR" => Category::Graphics,
  "Photography" => Category::Graphics,
  "Viewer" => Category::Graphics,
  "Network" => Category::Network,
  "Email" => Category::Network,
  "Dialup" => Category::Network,
  "InstantMessaging" => Category::Network,
  "Chat" => Category::Network,
  "IRCClient" => Category::Network,
  "Feed" => Category::Network,
  "FileTransfer" => Category::Network,
  "HamRadio" => Category::Network,
  "News" => Category::Network,
  "P2P" => Category::Network,
  "RemoteAccess" => Category::Network,
  "Telephony" => Category::Network,
  "Office" => Category::Office,
  "Calendar" => Category::Office,
  "ContactManagement" => Category::Office,
  "Dictionary" => Category::Office,
  "Chart" => Category::Office,
  "Finance" => Category::Office,
  "FlowChart" => Category::Office,
  "PDA" => Category::Office,
  "ProjectManagement" => Category::Office,
  "Presentation" => Category::Office,
  "Spreadsheet" => Category::Office,
  "WordProcessor" => Category::Office,
  "Publishing" => Category::Office,
  "Settings" => Category::Settings,
  "DesktopSettings" => Category::Settings,
  "HardwareSettings" => Category::Settings,
  "Printing" => Category::Settings,
  "PackageManager" => Category::Settings,
  "Security" => Category::Settings,
  "Accessibility" => Category::Settings,
  "System" => Category::System,
  "Emulator" => Category::System,
  "TerminalEmulator" => Category::System,
  "Filesystem" => Category::System,
  "Monitor" => Category::System,
  "Utility" => Category::Utility,
  "Archiving" => Category::Utility,
  "Compression" => Category::Utility,
  "FileTools" => Category::Utility,
  "FileManager" => Category::Utility,
  "Clock" => Category::Utility,
  "TextEditor" => Category::Utility,
};
